config/routes.rb
ReduApps::Application.routes.draw do
  root to: 'apps#index'

  resources :apps, only: [:index, :show] do
    match '/checkout'  => 'checkout#update', via: :post
    match '/checkout' => 'checkout#new', via: :get
    member do
      post 'rate'
    end
    resources :comments, only: [:index, :create, :destroy] do
      resources :answers, only: [:index, :create, :destroy]
    end
  end

  resources :users, only: [] do
    resources :favorites, only: [:index, :create, :destroy]
  end

  resources :user_sessions, only: [:create]
  delete 'logout' => "user_sessions#destroy", as: :logout

  ActionDispatch::Routing::Translator.translate_from_file('config/locales/routes.yml')
end

app/views/shared/_app.html.erb
<div class="apps-list-item general-list-item">
  <% if favorite_flag %>
    <%= link_to "Remover dos favoritos", user_favorite_path(current_user, App.favorited_by([app], current_user)),
                confirm: "Esta ação irá remover este aplicativo dos seus favoritos. Deseja continuar?", method: :delete,
                class: "general-list-item-close icon-close-gray_16_18 text-replacement" %>
  <% end %>
  <div class="general-list-item-body">
    <div class="general-list-item-column <%= add_app_favorite_class(favorite_flag) %>">
      <%= link_to app_path(app), title: app.name do %>
        <%= image_tag app.thumbnail(:medium), title: app.name, alt: app.name, size: "90x90" %>
      <% end %>
    </div>
    <div class="general-list-item-column <%= add_app_favorite_class(favorite_flag) %>">
      <h4 class="general-list-item-title">
        <%= link_to app.name, app_path(app),
            title: app.name, class: "general-list-item-title-link text-truncate" %>
      </h4>
      <span class="legend"><%= names_for(Category.get_by_kind(app, 'Nível')) %></span>
      <span class="legend" title="<%= app.author %>"><em>Autor:</em> <%= truncate(app.author, length: 60) %></span>
      <span class="legend"><em>Língua:</em> <%= app.language %></span>
      <% has_subarea = Category.get_by_kind(app, 'Subárea').length > 0 %>
      <% if Category.get_by_kind(app, 'Área').length > 0 %>
        <span class="legend">
          <em>Área:</em> <%= names_for(Category.get_by_kind(app, 'Área')) %><%= ':' if has_subarea %>
          <%= names_for(Category.get_by_kind(app, 'Subárea')) if has_subarea %>
        </span>
      <% end %>
    </div>
  </div>
  <div class="general-list-item-footer">
    <%= render "shared/app_rating_stars", rating: app.reputation_for(:rating).to_i %>
    <ul class="general-list-item-counters">
      <li class="general-list-item-counter icon-seen-gray_16_18-before">
        <%= app.views %>
      </li>
      <li class="general-list-item-counter icon-comment-gray_16_18-before">
        <%= count_comments_for(app) %>
      </li>
      <% specialized_comments = Comment.get_by_kind(app, :specialized).length %>
      <% if specialized_comments != 0 %>
        <li class="general-list-item-counter icon-specialist-gray_16_18-before">
          <%= specialized_comments %>
        </li>
      <% end %>
    </ul>
  </div>
  <% if favorite_flag %>
    <button class="button-default" data-toggle="modal-app" data-modal-title="<%= app.name %>" data-modal-subtitle="<%= app.author %>" data-modal-url="<%= app.core_url %>">Abrir</button>
  <% end %>
</div>
<% if display_separator(app_counter + 1, total) %>
  <hr>
<% end %>

app/views/shared/_app_rating_stars.html.erb
<% if rating > 0 %>
  <ol class="general-list-item-stars">
    <% rating.times do %>
      <li class="general-list-item-star">
        <span class="icon-star-full-gray_16_18 show text-replacement">Estrela</span>
      </li>
    <% end %>
  </ol>
<% end %>

app/views/shared/_apps_pagination.html.erb
<%= paginate @apps, outer_window: 1, inner_window: 4 %>

app/views/shared/_dropdown_sign_in.html.erb
<%= render partial: 'shared/form_sign_in' %>
<hr class="header-separator">
<div class="facebook-sign-in">
  <%= link_to "Entre com sua conta do Facebook", redu_static("auth/facebook?state=#{request.url}"), class: "facebook-sign-in-button" %>
</div>
<hr class="header-separator">
<div class="header-sign-in-recover">
  <%= link_to "Esqueceu seu login ou senha? Clique aqui", redu_static("recuperar_login_senha"), class: "link-secondary" %>
</div>

app/views/shared/_flash_message.html.erb
<% flash.each do |type, message| %>
  <div class="system-message message-<%= flash_message_class(type) %> fade in">
    <a data-dismiss="alert" class="message-close">×</a>
    <p><%= h(message) %></p>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="span4">
        <div class="footer-logo-wrapper">
          <%= link_to "http://tech.redu.com.br/",
              class: "footer-logo-link" do %>
              <h1 class="footer-logo-img sprite-logo-redu-tech-footer text-replacement">Redu Educational Technologies</h1>
          <% end %>
          <span class="footer-cnpj">CNPJ: 12.359.885 / 0001-07</span>
        </div>
      </div>
      <div class="span3">
        <ul class="footer-navigation">
          <li>
            <%= link_to "Sobre o Redu",
                redu_domain,
                title: "Sobre o Redu"
            %>
          </li>
          <li>
            <%= link_to "Segmentos",
                redu_static("#segmentos"),
                title: "Segmentos",
                class: "landing-scroll"
            %>
          </li>
          <li>
            <%= link_to "Vantagens",
                redu_static("#vantagens"),
                title: "Vantagens",
                class: "landing-scroll"
            %>
          </li>
          <li>
            <%= link_to "Funcionalidades",
                redu_static("#funcionalidades"),
                title: "Funcionalidades",
                class: "landing-scroll"
            %>
          </li>
          <li>
            <%= link_to "Planos",
                redu_static("#planos"),
                title: "Planos",
                class: "landing-scroll"
            %>
          </li>
        </ul>
      </div>
      <div class="span3">
        <ul class="footer-navigation">
          <li>
            <%= link_to "Blog",
                "http://blog.redu.com.br/",
                title: "Blog"
            %>
          </li>
          <li>
            <%= link_to "Desenvolvedores",
                "http://developers.redu.com.br/",
                title: "Desenvolvedores"
            %>
          </li>
          <li>
            <%= link_to "Política de Privacidade",
                "#modal-privacy-policy",
                title: "Política de Privacidade",
                "data-toggle" => "modal"
            %>
          </li>
          <li>
            <%= link_to "Termos de Uso",
                "#modal-tos",
                title: "Termos de Uso",
                "data-toggle" => "modal"
            %>
          </li>
        </ul>
        <%= render partial: "shared/modal_tos" %>
        <%= render partial: "shared/modal_privacy_policy" %>
      </div>
      <div class="span3">
        <div class="footer-social-networks-legend">
          <span class="legend">Siga-nos na web</span>
        </div>
        <div class="footer-social-networks">
          <%= link_to "Facebook", "https://www.facebook.com/redesocialeducacional", class: "footer-social-network sprite-social-facebook text-replacement", title: "Facebook" %>
          <%= link_to "Twitter", "http://twitter.com/redu_ead", class: "footer-social-network sprite-social-twitter text-replacement", title: "Twitter" %>
        </div>
      </div>
      <div class="span3">
        <div class="footer-contact link-container">
          <div class="row">
            <div class="span2">
              <h3>
                <%= link_to "Fale Conosco",
                      redu_static("contato"),
                      title: "Fale Conosco",
                      class: "link-target"
                %>
              </h3>
              <p class="legend">Dúvidas? Nosso suporte online pode lhe ajudar</p>
            </div>
            <div class="span1 alpha-half">
              <span class="footer-talk-to-us-balloons sprite-talk-to-us text-replacement" title="Fale Conosco">Fale conosco</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_form_search.html.erb
<%# Formulário de busca com filtros. %>
<%= form_tag(redu_static("busca"), :method => "GET", :class => "form-search form-search-filters form-search-expandable pull-left area-fix") do %>
  <div class="button-group area-prefix">
    <button class="form-search-filters-button button-default clearfix dropdown-toggle" data-toggle="dropdown">
      <span class="control-search-icon icon-basic-guide-gray_16_18 text-replacement pull-left">Filtrar</span>
      <span class="button-dropdown-arrow icon-arrow-down-gray_8_10 text-replacement">Expandir</span>
    </button>
    <span class="dropdown-arrow icon-arrow-up-dropdown-lightblue_20_8 text-replacement">Seta</span>
    <ul class="nav-global-profile-items dropdown-menu form-search-filters-dropdown">
      <li class="nav-global-profile-item">
        <label class="control-radio">
          <input type="radio" name="radio" value="geral" checked="checked"><span class="legend icon-basic-guide-gray_16_18-before">Busca Geral</span>
        </label>
      </li>
      <li class="nav-global-profile-item">
        <label class="control-radio">
          <input type="radio" name="radio" value="ambientes"><span class="legend icon-environment-gray_16_18-before">Ambientes</span>
        </label>
      </li>
      <li class="nav-global-profile-item">
        <label class="control-radio">
          <input type="radio" name="radio" value="perfil"><span class="legend icon-profile-gray_16_18-before">Perfil</span>
        </label>
      </li>
    </ul>
  </div>
  <%= text_field_tag(:q, nil, :placeholder => "Pesquise...", :class => "control-area area-infix") %>
  <button class="button-default area-suffix" type="submit">
    <span class="control-search-icon icon-magnifier-gray_16_18 text-replacement ">Buscar</span>
  </button>
<% end %>

app/views/shared/_form_sign_in.html.erb
<%= form_for @user_session || UserSession.new, remote: true, html: { class: "header-sign-in-form", id: "sign-in-form" } do |f| %>
  <div class="control-group">
    <div class="control-label">
      <%= f.label :login, "Login ou e-mail" %>
    </div>
    <div class="controls">
      <%= f.text_field :login, placeholder: "Seu login ou e-mail cadastrado" %>
      <%= concave_errors_for f.object, :login %>
    </div>
  </div>
  <div class="control-group">
    <div class="control-label">
      <%= f.label :password, "Senha" %>
    </div>
    <div class="controls">
      <%= f.password_field :password, placeholder: "Sua senha" %>
      <%= concave_errors_for f.object, :password %>
    </div>
  </div>
  <div class="header-sign-in-form-submit">
    <div class="control-group pull-left">
      <div class="controls">
        <div class="control-checkbox">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me, "Mantenha-me conectado", class: "legend" %>
        </div>
      </div>
    </div>
    <%= f.submit "Enviar", class: "button-primary pull-right" %>
  </div>
<% end %>

app/views/shared/_form_sign_up.html.erb
<form class="form-horizontal">
  <div class="modal-header modal-header-gray">
    <h3 class="modal-sign-up-title icon-add-friend-green_32_34-before">Cadastre-se no Redu.<br>É gratuito, rápido e fácil.</h3>
  </div>
  <div class="modal-body">
    <div class="modal-sign-up-section">
      <p>Caso tenha uma conta no Facebook, você pode evitar o trabalho de preencher formulários ao associar sua conta ao Redu. Desta forma, o cadastro é feito de forma automática.</p>
      <div class="facebook-sign-up">
        <a href="/auth/facebook" class="facebook-sign-up-button" value="login-facebook">Cadastre-se no Redu usando sua conta do Facebook</a>
        <span class="legend"><em>Opcional</em></span>
      </div>
    </div>
    <hr class="list-separator">
    <div class="modal-sign-up-section">
      <p>Ou preencha os formulários abaixo e crie seu perfil no Redu.</p>
    </div>
    <div class="row">
      <div class="span6">
        <div class="control-group control-big">
          <div class="control-label span2">
            <label for="user_first_name">Nome</label>
          </div>
          <div class="controls span4">
            <input id="user_first_name" name="user[first_name]" placeholder="Seu primeiro nome" size="30" type="text">
          </div>
        </div>
        <div class="control-group control-big">
          <div class="control-label span2">
            <label for="user_last_name">Sobrenome</label>
          </div>
          <div class="controls span4">
            <input id="user_last_name" name="user[last_name]" placeholder="Seu último nome" size="30" type="text">
          </div>
        </div>
      </div>
      <div class="span6">
        <div class="control-group control-big">
          <div class="control-label span2">
            <label for="user_email">E-mail</label>
          </div>
          <div class="controls span4">
            <input id="user_email" name="user[email]" placeholder="Seu e-mail de contato" size="30" type="text">
          </div>
        </div>
        <div class="control-group control-big">
          <div class="control-label span2">
            <label for="user_email_confirmation">Confirmação</label>
          </div>
          <div class="controls span4">
            <input id="user_email_confirmation" name="user[email_confirmation]" placeholder="Digite novamente o e-mail" size="30" type="text">
          </div>
        </div>
      </div>
    </div>
    <hr class="header-separator">
    <div class="row">
      <div class="span6">
        <div class="control-group control-big">
          <div class="control-label span2">
            <label for="user_login">Login</label>
          </div>
          <div class="controls span4">
            <input id="user_login" name="user[login]" placeholder="Como será o seu apelido?" size="30" type="text">
          </div>
        </div>
        <div class="row">
          <div class="span4 offset2">
            <div class="modal-sign-up-login-explaination">
              <p class="legend">O Login define como será o endereço de sua página no Redu.</p>
              <p class="legend">Ex.: redu.com.br/pessoas/<strong>seulogin</strong></p>
            </div>
          </div>
        </div>
      </div>
      <div class="span6">
        <div class="control-group control-big">
          <div class="control-label span2">
            <label for="user_password">Senha</label>
          </div>
          <div class="controls span4">
            <input id="user_password" name="user[password]" placeholder="Digite sua senha" size="30" type="password">
          </div>
        </div>
        <div class="control-group control-big">
          <div class="control-label span2">
            <label for="user_password_confirmation">Confirmação</label>
          </div>
          <div class="controls span4">
            <input id="user_password_confirmation" name="user[password_confirmation]" placeholder="Confirme sua senha" size="30" type="password">
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer clearfix">
    <div class="modal-sign-up-tos">
      <div class="control-group">
        <div class="controls">
          <div class="control-checkbox tos">
            <input id="user_tos" name="user[tos]" type="checkbox" value="1">
            <label for="user_tos">Aceito os <a href="#modal-tos" data-toggle="modal">Termos de Uso</a> da plataforma Redu.</label>
          </div>
        </div>
      </div>
    </div>
    <div class="modal-sign-up-buttons">
      <a href="/" class="button-big button-default" data-dismiss="modal" rel="nofollow">Cancelar</a>
      <input class="button-big button-success" name="commit" type="submit" value="Cadastrar sua conta">
    </div>
  </div>
</form>

app/views/shared/_header_not_logged_in.html.erb
<div class="header-not-logged-in">
  <div class="container">
    <div class="header-logo-wrapper">
      <%= link_to redu_domain, :title => "Redu", :class => "header-logo sprite-logo" do %>
        <h1 class="text-replacement" title="Redu">Redu</h1>
      <% end %>
      <div class="header-logo-title-wrapper">
        <h2 class="header-logo-title">Você ainda não se identificou no Redu.</h2>
        <span class="header-logo-legend legend">Entre com sua conta para acessar seus cursos, aulas e amigos.</span>
      </div>
    </div>
    <div class="header-buttons">
      <div class="header-button-sign-up">
        <span class="icon-add-friend-darkgray_32_34 text-replacement">Cadastrar</span>
        <%= link_to "Não possui conta? Cadastre-se, é grátis", redu_static("#modal-sign-up"), class: "button-big button-success pull-right" %>
      </div>
      <div class="header-button-sign-in">
        <span class="icon-profile-darkgray_32_34 text-replacement">Entrar</span>
        <div class="button-group dropdown pull-right">
          <button class="button-big button-primary dropdown-toggle" data-toggle="dropdown">Entre no Redu</button>
          <span class="dropdown-arrow icon-arrow-up-dropdown-lightblue_20_8 text-replacement">Seta</span>
          <div class="dropdown-menu">
            <%= render partial: "shared/dropdown_sign_in" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_privacy_policy.html.erb
<div id="modal-privacy-policy" class="modal hide modal-fill-height modal-grids-14 modal-landing">
  <div class="modal-header modal-header-gray">
    <h3 class="icon-privacy-policy-darkgray_32_34-before">Política de Privacidade</h3>
  </div>
  <div class="modal-body modal-scroll">
    <p>Essa política descreve as condutas e os procedimentos, adotados pelo Redu, acerca da coleta, do uso e da divulgação das informações relacionadas à utilização dos produtos e serviços da plataforma Redu.</p>

    <h5><strong>Da coleta e uso das informações</strong></h5>

    <p>As informações são coletadas com o intuído de aprimorar os serviços utilizados pelos nossos usuários. Essas são coletadas e utilizadas de diversas maneiras:</p>

    <p><strong>Informações solicitadas durante o registro:</strong> Ao criar ou reconfigurar uma conta no Redu, o usuário fornece algumas informações pessoais, como seu nome, nome de usuário, senha e endereço de e-mail. Algumas dessas informações, por exemplo, seu nome e nome de usuário, são listados publicamente, incluso na sua página de perfil e em resultados de pesquisa realizados no site.</p>

    <p><strong>Informações complementares:</strong> O usuário pode fornecer informações adicionais para tornar públicas, como uma breve biografia, sua localização, a instituição de ensino a que se vincula e/ou uma imagem.</p>

    <p><strong>Mensagens, vídeo-aulas, exames e outras informações públicas:</strong> Nossos serviços são principalmente concebidos para ajudá-lo a compartilhar as informações com outros usuários. Dessa forma, a maioria das informações postadas é pública, havendo a opção de torná-la privada. Incluindo-se nessa política não apenas as mensagens que o usuário postou, mas também os outros usuários que esse segue, a opção de marcar como favoritos e outras informações que vierem a ser disponibilizada pelo usuário.</p>

    <p><strong>Registro de dados:</strong> Nossos servidores automaticamente registram a informação criada pelo uso dos serviços. O registro de dados pode incluir informações como seu endereço IP, tipo de navegador, o domínio de referência, páginas visitadas, e os termos de busca. Outras ações, tais como a interação com os anúncios, também podem ser incluídas no registro de dados.</p>

    <p><strong>Cookies:</strong> Utilizamos cookies para recolher dados adicionais de uso do site e para melhorar nossos serviços. Um cookie é um pequeno arquivo de dados que são transferidos para o disco rígido do seu computador. O Redu pode utilizar cookies de sessão e cookies persistentes para entender melhor como o usuário interage com nossos serviços, para monitorar o uso agregado por nossos visitantes e tráfego web de roteamento em nossos serviços.</p>

    <p><strong>Serviços de terceiros:</strong> O Redu usa o Google Analytics para ajudar a entender o uso dos nossos serviços. Através do Google Analytics o Redu recolhe as informações enviadas pelo seu navegador, como parte de uma solicitação de página da web, incluindo cookies eo seu endereço IP. O Google também recebe informações e seu uso é regido por sua <a href="http://www.google.com/policies/privacy/" title="Política de Privacidade">Política de Privacidade da Google</a>.</p>

    <h5><strong>Do compartilhamento de divulgação de informações</strong></h5>

    <p>O Redu não compartilha, nem divulga suas informações privadas, exceto com o objetivo de fornecer aos usuários o produto e/ou serviços solicitados, tendo obtido para tanto a sua permissão, ou nas circunstâncias excepcionais descritas a seguir:</p>

    <p>Fornecemos as informações disponibilizadas, com os nossos parceiros. Essas empresas parceiras poderão usar os dados disponibilizados com o objetivo de auxiliar o Redu na prestação do serviço ao qual se destina. Contudo, tais empresas não possuem direito de compartilhar quaisquer informações com terceiros estranhos a essa relação.</p>

    <p>Podemos revelar suas informações, para atendermos a ordens judiciais nos termos da legislação em vigor, ou em processos judiciais para estabelecer ou exercer nossos direitos legais ou empreender defesa contra ações judiciais. Bem como, quando acreditarmos de boa-fé ser necessário compartilhar informações com o objetivo de investigar, impedir ou adotar medidas relativas a atividades ilegais, suspeitas de fraude, situações envolvendo possíveis ameaças à segurança física de qualquer pessoa, violações do Termo de uso do Redu ou com outros objetivos, com procedimentos especificados e autorizados pela&nbsp; lei.</p>

    <p>Caso o Redu esteja envolvido em uma falência, fusão, aquisição, reestruturação ou venda de ativos, suas informações podem ser vendidas ou transferidas como parte dessa transação. As promessas nesta política de privacidade serão aplicáveis às suas informações como transferidos para a nova entidade.</p>

    <p>Podemos compartilhar ou divulgar as suas informações que não são privadas, agregados ou informações pessoais, como seus comentários públicos ou o número de usuários que clicaram em um link específico.</p>

    <h5><strong>Da confidencialidade e segurança</strong></h5>

    <p>Limitamos o acesso às informações pessoais que temos sobre o usuário aos nossos empregados que, conforme acreditamos, possam ter necessidade delas para exercer suas funções que visam fornecer a você nossos produtos e serviços.</p>

    <h5><strong>Das mudanças nesta política</strong></h5>

    <p>O Redu pode atualizar essa política. Havendo alguma alteração em nossa Política de Privacidade, enviaremos uma notificação para o endereço de e-mail associado a conta do usuário. Ao continuar a utilizar os serviços após as alterações se tornarem eficaz, o usuário concorda em ficar vinculado a essa.</p>

    <p>Qualquer dúvida ou sugestão sobre nossa política de privacidade, por favor envie um e-mail para <a href="mailto:privacidade@redu.com.br" title="privacidade@redu.com.br">privacidade@redu.com.br</a></p>

    <p>Atualizado pela última vez em: <em>março de 2012</em></p>
  </div>
  <div class="modal-footer">
    <button data-dismiss="modal" class="button-default">Voltar</button>
  </div>
</div>

app/views/shared/_nav_global.html.erb
<div class="nav-global nav-global-fixed-top">
  <style>
    .main-wrapper { padding-top: 42px; }
  </style>
  <div class="nav-global-inner">
    <div class="nav-global-container">
      <h1>
        <%= link_to "Redu", redu_domain, class: "nav-global-brand logo-redu-gray_140_40 text-replacement", title: "Redu" %>
      </h1>
      <div class="nav-global-buttons">
        <%= link_to "Início", redu_domain, class: "nav-global-button", title: "Início" %>
        <%= link_to "Ensine", redu_static("ensine"), class: "nav-global-button", title: "Ensine" %>
        <%= link_to "Ambientes", redu_static("ambientes"), class: "nav-global-button", title: "Ambientes" %>
        <%= link_to "Aplicativos", root_path, class: "nav-global-button nav-global-button-active", title: "Aplicativos" %>
      </div>
      <div class="nav-global-right-area">
        <%= render "shared/form_search" %>
        <div class="nav-global-buttons-dropdown button-toolbar pull-right">
          <div class="button-group">
            <button class="button-default nav-global-button-dropdown dropdown-toggle icon-profile-2-lightblue_16_18-before" data-toggle="dropdown">
              <span class="button-dropdown-arrow icon-arrow-down-lightblue_8_10"></span>
            </button>
            <div class="dropdown-menu nav-global-profile-dropdown">
              <div class="arrow"></div>
              <div class="nav-global-profile-header">
                <%= current_user.display_name %>
              </div>
              <ul class="nav-global-profile-items">
                <li class="nav-global-profile-item">
                  <%= link_to "Meu Perfil", redu_user_static, class: "nav-global-profile-item-link icon-profile-lightblue_16_18-before", title: "Meu Perfil" %>
                  <%= link_to "editar", redu_user_static("editar"), class: "nav-global-profile-item-link-secondary link-secondary", title: "Editar perfil" %>
                </li>
                <li class="nav-global-profile-item">
                  <%= link_to "Mensagens", redu_user_static("messages"), class: "nav-global-profile-item-link icon-message-lightblue_16_18-before", title: "Mensagens" %>
                </li>
                <li class="nav-global-profile-item">
                  <%= link_to "Configurações", redu_user_static("editar"), class: "nav-global-profile-item-link icon-manage-lightblue_16_18-before", title: "Configurações" %>
                </li>
                <li class="nav-global-profile-item">
                  <%= link_to "Sair", logout_path, remote: true, method: :delete, title: "Sair", class: "nav-global-profile-item-link nav-global-profile-item-link-iconless" %>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<%# Formulário de busca. %>
<%= form_tag apps_path, method: :get, class: "form-search area-fix form-search-expandable apps-portal-search-form" do %>
  <%= text_field_tag :search, params[:search], class: "control-area area-infix", placeholder: "Procure Aplicativos...", "data-toggle" => "#apps-portal-breadcrumb" %>
  <button class="button-default area-suffix" type="submit">
    <span class="control-search-icon icon-magnifier-gray_16_18 text-replacement">Busca</span>
  </button>
<% end %>