config/routes.rb
ReduApps::Application.routes.draw do
  root to: 'apps#index'

  resources :apps, only: [:index, :show] do
    match '/checkout'  => 'checkout#update', via: :post
    match '/checkout' => 'checkout#new', via: :get
    member do
      post 'rate'
    end
    resources :comments, only: [:index, :create, :destroy] do
      resources :answers, only: [:index, :create, :destroy]
    end
  end

  resources :users, only: [] do
    resources :favorites, only: [:index, :create, :destroy]
  end

  resources :user_sessions, only: [:create]
  delete 'logout' => "user_sessions#destroy", as: :logout

  ActionDispatch::Routing::Translator.translate_from_file('config/locales/routes.yml')
end

app/models/answer.rb
class Answer < Comment
  validates_presence_of :in_response_to
end

app/controllers/answers_controller.rb
class AnswersController < CommentsController

  def index
    @answers = Answer.where(in_response_to_id: params[:comment_id])
    authorize! :read, Answer

    respond_to do |format|
      format.js
    end
  end

end

app/views/answers/_answer.html.erb
<%#
  Resposta dos comentários.

  Variáveis:
    answer: a resposta.
    total: a quantidade total de respostas.
%>

<li id="comment-<%= answer.id %>">
  <hr>
  <div class="response">
    <% if can? :destroy, answer %>
      <%= link_to 'Apagar Resposta', app_comment_path(answer.app, answer),
                 confirm: 'Esta ação irá apagar sua resposta. Deseja continuar?',
                 method: :delete, remote: true,
                 class: "icon-close icon-close-gray_16_18 text-replacement" %>
    <% end %>
    <%= link_to redu_user_static("", answer.author), class: "author-thumbnail" do %>
      <%= image_tag answer.author.thumbnail.url(:small), alt: answer.author.display_name, title: answer.author.display_name, size: "32x32" %>
    <% end %>
    <%= link_to answer.author.display_name, redu_user_static("", answer.author), class: "link-name" %>
    <span class="action">
      respondeu:
    </span>
    <span class="date legend">
      <%= l answer.created_at %>
    </span>
    <div class="status-content">
      <%= answer.body %>
    </div>
  </div>
</li>

app/views/answers/index.js.erb
var $container = $('#comments-for-<%= params[:comment_id] %>');
$container.find('.comments').html('<%= escape_javascript render partial: "answer", collection: @answers, locals: { comment: @comment, total: @answers.length } %>');
$container.find('.show-more, .last-responses').remove();