config/routes.rb
ReduApps::Application.routes.draw do
  root to: 'apps#index'

  resources :apps, only: [:index, :show] do
    match '/checkout'  => 'checkout#update', via: :post
    match '/checkout' => 'checkout#new', via: :get
    member do
      post 'rate'
    end
    resources :comments, only: [:index, :create, :destroy] do
      resources :answers, only: [:index, :create, :destroy]
    end
  end

  resources :users, only: [] do
    resources :favorites, only: [:index, :create, :destroy]
  end

  resources :user_sessions, only: [:create]
  delete 'logout' => "user_sessions#destroy", as: :logout

  ActionDispatch::Routing::Translator.translate_from_file('config/locales/routes.yml')
end

app/views/apps/_common_comment.html.erb
<hr class="list-separator">
<li class="status">
  <div class="status-text">
    <%= link_to redu_user_static("", common_comment.author), class: "icon-link" do %>
      <%= image_tag common_comment.author.thumbnail.url(:medium), alt: common_comment.author.display_name, title: common_comment.author.display_name %>
    <% end %>
    <%= link_to common_comment.author.display_name, redu_user_static("", common_comment.author), class: "link-name" %>
    comentou sobre este aplicativo:
    <%= link_to_if (common_comment.author == current_user), 'Apagar Comentário', [common_comment.app, common_comment],
               :confirm => 'Ao apagar este comentário, você também removerá todas as respostas. Deseja continuar?',
               :method => :delete,
               :class => "close icon-close-gray_16_18 replacement" %>
    <span class="date"><%= l common_comment.created_at %></span>
  </div>
  <div class="status-container">
    <div class="status-content">
      <div class="post-text">
        <p class="input-user">
          <%= common_comment.body %>
        </p>
      </div>
    </div>

  <%# Respostas ao comentário %>
  <% if common_comment.answers.length != 0 %>
    <ol id="comments-for-<%= common_comment.id %>" class="responses status-content">
      <% if common_comment.answers.length > 2 %>
        <li class="last-responses">
          <p class="legend">Visualizando as últimas respostas...</p>
          <hr>
        </li>
      <% end %>
      <div class="comments">
        <%= render partial: 'comment_answer', collection: common_comment.answers.last(2),
                   locals: { comment: common_comment, total: max_2_answers(common_comment.answers.length) } %>
      </div>
      <% if common_comment.answers.length > 2 %>
        <div class="show-more">
          <hr>
          <li class="all-responses">
            <%= link_to "Mostrar todas as #{common_comment.answers.length} respostas",
                        app_path(@app, :'show-answers-for' => common_comment.id),
                        remote: true, class: "link-secondary" %>
          </li>
        </div>
      <% end %>
    </ol>
  <% end %>
  </div>
  <ul class="actions clearfix">
    <li>
      <a class="icon-reply-gray_8_10-before reply-status" href="#">Responder</a>
    </li>
  </ul>
  <%= render "create_response", klass: nil, model_object: [@app, common_comment, @app.comments.build], comment_type: "answer" %>
</li>

app/views/apps/_create_response.html.erb
<%#
  Renderiza o balão cinza com a área de texto de responder.

  Variáveis locais:
    klass: classe adicional a ser adicionada no wrapper.
    model_object: o modelo de objeto usado pelo formulário.
    comment_kind: indica o tipo de resposta (common, specialized ou answer).
%>
<div class="create-response <%= klass %>">
  <%= form_for(model_object, remote: true) do |f| %>
    <fieldset>
      <%= f.text_area :body, rows: "6" %>
      <%= f.hidden_field :kind, value: comment_kind %>
      <%= f.hidden_field :author, value: current_user.id %>
      <div class="status-buttons">
        <%= link_to "Cancelar", nil, class: "button-default cancel" %>
        <%= submit_tag "Enviar", class: "button-primary" %>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/apps/_star.html.erb
<%#
  Renderiza uma estrela.
  Caso algum usuário estiver logado, a estrela é clicável para o voto. Caso contrário a estrela é apenas mostrada.

  Variáveis locais:
    index: indica o número ordenal da estrela.
    type: indica o tipo de estrela (lightgray, gray ou blue).
%>
<li class="oer-star">
  <% if can? :rate, @app %>
    <%= link_to "#{index+1}", rate_app_path(@app, rating: index+1), method: "post", remote: true, class: "icon-star-full-" + type + "_16_18 show text-replacement", "data-star-color" => type %>
  <% else %>
    <span class="icon-star-full-<%= type %>_16_18 show text-replacement"><%= index + 1 %></span>
  <% end %>
</li>

app/views/apps/_stars.html.erb
<div class="oer-rating">
  <div class="oer-stars-n-value">
    <%# Estrelas. %>
    <ol class="oer-stars<%= " oer-stars-user-rated" if can? :rate, @app %>">
      <% user_rating = @user_rating.to_i || 0 %>
      <% index = user_rating || 0 %>
      <%# Renderiza as estrelas azuis da nota do usuário. %>
      <% if can? :rate, @app %>
        <% user_rating.times do |n| %>
          <%= render "star", index: n, type: "blue" %>
        <% end %>
      <% end %>
      <%# Renderiza as estrelas cinza escuro da média de classificação. %>
      <% if @app_rating > user_rating %>
        <% (@app_rating - user_rating).to_i.times do |n| %>
          <%= render "star", index: index, type: "gray" %>
          <% index += 1 %>
        <% end %>
      <% end %>
      <%# Renderiza as estrelas cinza claro restantes. %>
      <% (5 - index).times do |n| %>
        <%= render "star", index: index, type: "lightgray" %>
        <% index += 1 %>
      <% end %>
    </ol>

    <%# Nota média. %>
    <span class="oer-rating-value"><%= number_with_precision(@app_rating, :locale => :en, :precision => 1, :strip_insignificant_zeros => true) %><span class="oer-rating-value-max">/5</span></span>
  </div>

  <%# Nota do usuário. %>
  <% if can? :rate, @app %>
    <span class="legend show">
      <% if @evaluated %>
        Você classificou em <%= t "star", count: user_rating %>.
      <% else %>
        Classifique este Recurso.
      <% end %>
    </span>
  <% end %>
</div>

app/views/apps/index.html.erb
<% unless params.include? :search %>
  <div class="apps-portal-oer">
    <div class="apps-portal-oer-explaination">
      <span class="apps-portal-oer-close icon-close-gray_16_18 text-replacement">Fechar</span>
      <h3 class="apps-portal-oer-explaination-title">O que são R.E.A.s?</h3>
      <p>Recursos Educacionais Abertos são <em>materiais</em> de ensino, aprendizado e pesquisa em qualquer suporte ou mídia, que estão sob domínio público, ou estão licenciados de maneira aberta, permitindo que sejam utilizados ou adaptados por terceiros. O uso de formatos técnicos abertos facilita o acesso e o reuso potencial dos recursos publicados digitalmente. Recursos Educacionais Abertos podem incluir cursos completos, partes de cursos, módulos, livros didáticos, artigos de pesquisa, vídeos, testes, software, e qualquer outra ferramenta, material ou técnica que possa apoiar o acesso ao conhecimento. (<a href="http://rea.net.br/site/o-que-e-rea/" title="UNESCO/Comunidade REA Brasil">UNESCO/Comunidade REA Brasil</a>)</p>
    </div>
  </div>
<% end %>

<%= render "shared/search" %>

<%# Abas de navegação %>
<%= render_navigation context: :tabs %>

<% if @apps.size == 0 %>

  <div class="oer-apps-none">
    <%= image_tag "icon-api-gray_128_130.png", size: "128x130" %>
    <p>Sentimos muito, mas não achamos resultado para “<%= params[:search] %>”. Tente outro termo.</p>
  </div>

<% else %>

  <% unless !params.include? :search %>
    <div class="apps-portal-search-messages">
      <span class="apps-portal-search-message">
        Você buscou por <strong>“<%= params[:search] %>”</strong>.
        Achamos <strong><%= @results_counter %></strong> <%= t 'result', count: @results_counter %>.
      </span>
      <span class="apps-portal-search-message">Use os filtros abaixo para facilitar a busca.</span>
    </div>
  <% end %>

  <div class="apps-portal-filters">
    <%= render_navigation context: :filters, renderer: :links %>
  </div>

  <div class="oer-apps-wrapper">
    <div id="apps" class="apps-list">
      <%= render partial: 'shared/app', collection: @apps,
                 locals: { favorite_flag: false, total: @apps.count } %>
    </div>
  </div>

  <% if @apps.num_pages > 1 %>
    <hr class="list-separator">

    <div id="paginator" class="pagination">
      <%= render 'shared/apps_pagination' %>
    </div>
  <% end %>

<% end %>

app/views/apps/index.js.erb
$('#apps').append('<%= escape_javascript render partial: "shared/app", collection: @apps, locals: { favorite_flag: false } %>');
$('#paginator').html("<%= escape_javascript(link_to_next_page(@apps, 'Mostrar mais...', {remote: true, params: {filter: @filter, search: @search}, class: 'button-default icon-arrow-down-pagination-gray_16_18-before'})) %>")

app/views/apps/preview.html.erb
<h1><%= @app.name %></h1>
<iframe src=<%=@app.url%>></iframe>

app/views/apps/rate.js.erb
$('.oer-rating').html('<%= escape_javascript render partial: "stars" %>');
$('#evaluation-count').html('<%= t 'evaluation', count: @evaluations %>');

app/views/apps/show.html.erb
<div class="oer-main-wrapper">
  <%= render "shared/search" %>
  <div class="oer-header clearfix">
    <% if @favorite %>
      <span class="icon-favorite-blue_32_34 text-replacement oer-favorite-icon" rel="tooltip" title="Este é um Aplicativo Favorito." data-placement="top">Favorito</span>
    <% end %>
    <%= content_tag :h3, @app.name, class: "oer-title" %>
  </div>

  <div class="oer-body clearfix">
    <%# Coluna da esquerda. %>
    <div class="oer-left-sidebar">
      <%# Thumbnail. %>
      <%= image_tag @app.thumbnail.url(:large), alt: @app.name, title: @app.name, class: "oer-thumbnail", size: "160x160" %>

      <%# Área de classificação. %>
      <%= render "stars" %>

      <%# Contadores. %>
      <ul class="oer-counters">
        <li id="evaluation-count" class="oer-counter legend icon-star-empty-gray_16_18-before">
          <%= t 'evaluation', count: @evaluations %>.
        </li>
        <li class="oer-counter legend icon-favorite-gray_16_18-before">
          <%= t 'favorite', count: @app.users.count %>.
        </li>
        <li class="oer-counter legend icon-seen-gray_16_18-before">
          <%= t 'views', count: @app.views %>.
        </li>
        <% if @specialized_comments.length > 0 %>
          <li class="oer-counter legend icon-specialist-gray_16_18-before">
            <%= t 'review', count: @specialized_comments.length %>.
          </li>
        <% end %>
        <li class="oer-counter legend icon-comment-gray_16_18-before">
          <%= t 'comment',
                count: count_comments_for(@app) %>.
        </li>
      </ul>
    </div>

    <%# Coluna do meio. %>
    <div class="oer-middle-sidebar">

      <div class="oer-info-n-buttons clearfix">
        <%# Informações. %>
        <ul class="oer-info">
          <li class="oer-info-item">
            <em class="oer-info-key">Autor:</em>
            <span class="oer-info-value"><%= @app.author %></span>
          </li>
          <% @app_categories.each do |category| %>
            <li class="oer-info-item">
              <em class="oer-info-key"><%= category.first %>:</em>
              <span class="oer-info-value"><%= category.second.join(", ") %></span>
            </li>
          <% end %>
          <li class="oer-info-item">
            <em class="oer-info-key">Objetivo:</em>
            <span class="oer-info-value"><%= @app.objective %></span>
          </li>
          <li class="oer-info-item">
            <em class="oer-info-key">Sinopse:</em>
            <span class="oer-info-value"><%= @app.synopsis %></span>
          </li>
          <li class="oer-info-item">
            <em class="oer-info-key">Descrição:</em>
            <span class="oer-info-value"><%= @app.description %></span>
          </li>
        </ul>

        <%# Botões. %>
        <div class="oer-buttons">
          <button class="button-default" data-toggle="modal-app" data-modal-title="<%= @app.name %>" data-modal-subtitle="<%= @app.author %>" data-modal-url="<%= @app.core_url %>">Abrir este Recurso</button>
          <% if can? :create, UserAppAssociation.new(app: @app)   %>
            <%= form_tag user_favorites_path(current_user), method: "post" do %>
              <%= hidden_field_tag :app_id , @app.id %>
              <%= content_tag :button, type: :submit, class: "button-primary" do %>
                Adicionar a Favoritos
              <% end %>
            <% end %>
          <% end %>
          <% if can? :checkout, @app %>
            <%= form_tag app_checkout_path(@app, previous_step: 0), method: :post, remote: true do %>
              <%= content_tag :button, "Adicionar à Disciplina", type: :submit, class: "button-success" %>
            <% end %>
          <% end %>
          <% if can? :destroy, @favorite %>
            <%= link_to "Remover dos Favoritos", user_favorite_path(current_user, @favorite), method: "delete", class: "icon-favorite-delete-lightblue_16_18-before", title: "Remover dos Favoritos" %>
          <% end %>
        </div>
      </div>

      <div class="oer-meta-wrapper">
        <ul class="oer-meta meta-data-column-1">
          <li class="oer-meta-item">
            <span class="legend"><em>Publicador:</em> <%= verify_availability(@app.publishers) %></span>
          </li>
          <li class="oer-meta-item">
            <span class="legend"><em>Detentor dos Direitos:</em> <%= verify_availability(@app.copyright) %></span>
          </li>
          <li class="oer-meta-item">
            <span class="legend"><em>Submetido por:</em> <%= verify_availability(@app.submitters) %></span>
          </li>
        </ul>

        <ul class="oer-meta meta-data-column-2">
          <li class="oer-meta-item">
            <span class="legend"><em>Classificação:</em> <%= verify_availability(@app.classification) %></span>
          </li>
          <li class="oer-meta-item">
            <span class="legend"><em>Língua:</em> <%= verify_availability(@app.language) %></span>
          </li>
          <li class="oer-meta-item">
            <span class="legend"><em>País de Origem:</em> <%= verify_availability(@app.country) %></span>
          </li>
          <li class="oer-meta-item">
            <span class="legend"><em>Origem:</em> <%= verify_availability(@app.url, true) %></span>
          </li>
        </ul>
      </div>

      <div class="oer-images">
        <% @app.screen_shots.each do |ss| %>
          <%= image_tag ss.screen.url(:unique), alt: "Prévia", title: "Prévia", class: screen_shot_class(@app.screen_shots.length), size: "700x200" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%# Comentários dos especialistas. %>
<ol id="specialized-comments" class="status-list">
  <%= render partial: 'comments/specialized_comment', collection: @specialized_comments %>
</ol>

<% if can? :create, Comment %>
  <hr class="list-separator">
<% end %>

<%# Botões de comentários. %>
<% if can? :create, Comment %>
  <div class="content-section oer-comments reply-buttons <%= "can-review" if can? :create, Comment.new(kind: :specialized) %>">
    <ul class="reply-buttons-list">
      <li>
        <button class="button-primary button-big reply-status button-comment icon-comment-white_blue_32_34-before" title="Comentar sobre este aplicativo">Comentar</button>
      </li>
      <% if can? :create, Comment.new(kind: :specialized) %>
        <li>
          <button class="button-primary button-big reply-status button-review icon-specialist-white_blue_32_34-before">Escrever uma resenha</button>
        </li>
      <% end %>
    </ul>
    <%= render "comments/form", klass: "create-status tab-left", array_for_url: [@app, @app.comments.build(kind: "common")] %>
    <% if can? :create, Comment.new(kind: :specialized) %>
      <%= render "comments/form", klass: "create-status tab-right", array_for_url: [@app, @app.comments.build(kind: "specialized")] %>
    <% end %>
  </div>
<% end %>

<%# Comentários comuns. %>
<% if can? :read, Comment %>
  <ol id="comments" class="status-list">
    <%= render partial: 'comments/common_comment', collection: @common_comments %>
  </ol>
  <% unless @common_comments.last_page? %>
    <div id="pagination-wrapper">
      <hr class="list-separator">
      <div id="paginator" class="pagination">
        <%= link_to_unless @common_comments.last_page?, "Mostrar mais...",
          app_comments_path(@app, page: (@common_comments.current_page + 1)), :rel => 'next', remote: true,
          class: "button-default icon-arrow-down-pagination-gray_16_18-before" %>
      </div>
    </div>
  <% end %>
<% end %>